const mongoose = require('mongoose');

const tblStockProductSchema = new mongoose.Schema({
  id: Number,
  product_ref: Number,
  description: String,
  serialno: String,
  qadone: Boolean,
  qty: Number,
  dateofmanufacturing: Date,
  expirydate: Date,
  waranty_service: String,
  location: String,
  barcode: String,
  isbarcodegenerated: Boolean,
  status: String,
  receivedby_ref: Number,
  receiveddate: Date,
  invoice_ref: Number,
  store_ref: Number,
  rate: Number,
  discountmode: String,
  discount: Number,
  total: Number,
  sellingprice: Number,
  createddate: Date,
  gst: Number,
  productgroupbyguid: String,
  issellingpriceupdate: Boolean,
  mrp: Number,
  MiscCharge: Number,
  Margin: Number,
  baseunit: String,
  subqty: Number,
  subunit: String,
  soldqty: Number,
  lotnumber: String,
  hsn: String,
  defectiveqty: Number,
  saledefectiveqty: Number,
  landingrate: Number,
  invoice: {
    id: Number,
    invoiceno: String,
    invoicedate: Date,
    qty: Number,
    rate: Number,
    discountmode: String,
    discount: Number,
    roundoff: Number,
    total: Number,
    defectiveqty: Number,
    supplier_ref: Number,
    createddate: Date,
    storeid_ref: Number,
    issellingpriceupdated: Boolean,
    sellingpriceupdateduser_ref: Number,
    others: Number,
    Transportcharges: Number,
    dcno: String,
    dcdate: Date,
    discountappliedon: String,
    po_ref: String,
    shipping_address_ref: String,
    erpuniqueref: String,
    grn: String,
  },
  cnStockproduct: Number,
  transportCharges: Number,
  PurchaseCreditNote: {
    id : Number,
    creditnotenumber : String,
    creditnotedate : Date,
    remarks : String,
    total : Number,
    creditnotestatus : String,
    supplier_ref : Number,
    picture_ref : Number,
    isapproved : Boolean,
    store_ref : Number,
    createddatetime : Date,
    redeemedamount : Number
  }
},{collection:"tblstockproduct"});

const tblStockProduct = mongoose.model('tblStockProductSchema', tblStockProductSchema);

module.exports = tblStockProduct;
